### ISSUE TITLE
Credentials in Repo

### ISSUE THREAD

**Issue by freeone3000** [json-lou/qhacks-2019#1]
https://github.com/json-lou/qhacks-2019/blob/88eaeec73e086cd9c0dc6c8f08cced4aa64292e7/be-python/speech-to-text/speech-to-text.py#L24
https://github.com/json-lou/qhacks-2019/blob/88eaeec73e086cd9c0dc6c8f08cced4aa64292e7/be-python/speech-to-text/speech-to-text.py#L31
https://github.com/json-lou/qhacks-2019/blob/88eaeec73e086cd9c0dc6c8f08cced4aa64292e7/be-python/speech-to-text/freq-words.py#L67
https://github.com/json-lou/qhacks-2019/blob/88eaeec73e086cd9c0dc6c8f08cced4aa64292e7/be-python/vision-to-text/vidText.py#L48

You might want to remove the commit that added these from history and repush your branches. You might also want to regenerate your IBM key through the service dashboard and change the password on your mongo database.

**Comment by brittanylau** [comment]
Oops! Thanks for the heads up, James. We've regenerated the key and password!
